config/routes.rb
Rails.application.routes.draw do

  root 'companies#index'
  get '/auth/github/callback' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', :as => :logout
  get 'about' => 'abouts#index'

  resources :companies, only: [:index, :new, :create] do
    collection do
      get '/stats', to: 'companies#charts'
      get '/top-cities', to: 'companies#top_cities'
      get '/:country_code/states', to: 'companies#states'
      get '/:state_code/cities', to: 'companies#cities'
    end
  end

  get 'download/stats', to: 'companies#csv', constraints: {format: :csv}

  resources :users, only: [:new, :update] do
    collection do
      post '/new', to: 'users#update'
      get '/profile', to: 'users#show'
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :company_staff_stats
  has_many :users, through: :company_staff_stats
  belongs_to :headquarter
  belongs_to :company_size_tier

  def number_of_female_eng
    company_staff_stats.approved.average(:num_female_eng).to_i
  end

  def number_of_male_eng
    number_of_eng - number_of_female_eng
  end

  def number_of_eng
    company_staff_stats.approved.average(:num_eng).to_i
  end

  def female_ratio
    number_of_female_eng / number_of_eng.to_f
  end

  def male_ratio
    number_of_male_eng / number_of_eng.to_f
  end

  def approved?
    company_staff_stats.approved.present?
  end

end

app/controllers/companies_controller.rb
require 'uri'
require 'csv'
include SanitizeUrl

class CompaniesController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :states, :cities]

  def index
    begin
    @thoughts                = Thought.approved.limit(50).order("RAND()")
    @company_stats           = CompanyStaffStat.approved

    # RATIO PIE CHART
    total_num_females        = @company_stats.sum(:num_female_eng)
    total_num_engineers      = @company_stats.sum(:num_eng)
    total_num_males          = total_num_engineers - total_num_females
    female_percentage        = total_num_females / total_num_engineers.to_f
    gon.stats_count          = @company_stats.size
    gon.female_percentage    = female_percentage
    gon.female_engineers_num = total_num_females.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
    gon.male_percentage      = 1 - female_percentage
    gon.male_engineers_num   = total_num_males.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse

    # CITY DISTRIBUTION CHART
    # select the top 10 cities for startup hqs in terms of popularity in order of hq id, occurance and city

    # instead of a map, we can show a stacked bar chart with top cities and their count of occurance versus their female engineer percentage
    @top_hq_cities      = ActiveRecord::Base.connection.execute("SELECT c.headquarter_id, COUNT(c.headquarter_id), hq.city, hq.state, hq.country FROM companies as c JOIN headquarters as hq WHERE c.headquarter_id = hq.id GROUP BY headquarter_id ORDER BY COUNT(headquarter_id) DESC LIMIT 10;")

    count = []
    hq_ids = []
    @top_hq_cities.each do |sql|
      hq_ids << sql.first
      count << sql[1]
    end
    gon.count = count
    gon.companies_count = Company.count
    hqs = Headquarter.where(id: hq_ids)
    gon.hq_female_ratio = hqs.map {|hq| hq.average_female_ratio*100}
    gon.hq_names = hqs.map(&:location_string)

    # TOP 10 COMPANIES BAR CHART
    @companies = Company.select(&:approved?).sort_by(&:female_ratio).last(10).reverse
    gon.company_names   = @companies.map(&:name)
    gon.female_ratio = @companies.map{ |c| c.female_ratio * 100}
  rescue => e
    p e
    p e.message
    raise e
  end
  end

  def new
    @user    = current_user
    @company = Company.new
    @company_size_tier = CompanySizeTier.all
    # let's delete a extra pair and move US, UK, CA to the top of the list
    countries_hash = CS.get.delete_if {|k, _| [:COUNTRY_ISO_CODE, :US, :GB, :CA].include? k }
    @countries = Hash[countries_hash.sort_by{|_, v| v}].map {|code, name| [name, code.to_s]}.unshift(["United States", "US"], ["United Kingdom", "GB"], ["Canada", "CA"])
  end

  def states
    @states = CS.states(params[:country_code])

    respond_to do |format|
      format.json { render json: @states }
    end
  end

  def cities
    @cities = CS.cities(params[:state_code])
    respond_to do |format|
      format.json { render json: @cities }
    end
  end

  def create
    # redirect user from this page if they are not signed in
    @user         = current_user

    # let's do some url sanitation and standardization so it's not a nightmare to store in db
    sanitized_url = sanitize_url(params[:company][:url].downcase.strip)

    if sanitized_url.is_valid_url?
      parsed_url  = URI.parse(sanitized_url)
    else
      flash[:error] = "Please enter a valid URL"
      redirect_to :back and return
    end

    host_name           = parsed_url.host.scan(/^(www.)/).present? ? parsed_url.host : ("www." + parsed_url.host)

    @company            = Company.where(url: host_name).first || Company.new
    @num_eng            = params[:company][:company_staff_stat][:num_eng].to_i
    @num_female_eng = params[:company][:company_staff_stat][:num_female_eng].to_i
    @company_size_tier  = CompanySizeTier.find(params[:company][:company_size_tier_id].to_i)

    if !(0..@company_size_tier.high).include?(@num_eng)
      flash[:error] = "Please choose a valid company size tier value"
      redirect_to :back and return
    elsif @num_female_eng > @num_eng
      flash[:error] = "Please enter a valid engineer stats value"
      redirect_to :back and return
    end

    Honeybadger.context({
      user_id:        @user.id,
      company_id:     @company.try(:id),
      company_name:   params[:company][:name].titleize,
      original_url:   params[:company][:url].downcase.strip,
      sanitized_url:  host_name,
      public_status:  params[:company][:is_public],
      company_size_tier_id: @company_size_tier.id,
      num_female_eng: @num_female_eng,
      num_eng:        @num_eng,
      city:           params[:company][:headquarter][:city],
      state:          params[:company][:headquarter][:state],
      country:        params[:company][:headquarter][:country]
    })

    # TODO: if found a match, what should it do?
    if @company.persisted?
      @new_stat = CompanyStaffStat.new(
        company_id:     @company.id,
        user_id:        @user.id,
        num_female_eng: @num_female_eng,
        num_eng:        @num_eng
      )

      if @new_stat.save
        @new_stat.company_id = @company.id
        @new_stat.save!
        flash[:notice] = "Thank you for your contribution!"
        redirect_to new_user_path and return
      else
        # TODO: be more specific with the error here
        flash[:notice] = "Sorry something went wrong with you submission"
        redirect_to :back and return
      end
    else
      ActiveRecord::Base.transaction do
        @company.name           = params[:company][:name].titleize
        @company.url            = host_name
        @company.is_public      = params[:company][:is_public] == "true"
        @company.company_size_tier_id = @company_size_tier.id

        @new_stat                = CompanyStaffStat.new(
          user_id:        @user.id,
          num_female_eng: @num_female_eng,
          num_eng:        @num_eng
        )

        city    = params[:company][:headquarter][:city]
        state   = params[:company][:headquarter][:state]
        country = params[:company][:headquarter][:country]

        headquarter = Headquarter.where(city: city, state: state, country: country).first

        if headquarter.nil?
          new_headquarter         = Headquarter.new
          new_headquarter.city    = city
          new_headquarter.state   = state
          new_headquarter.country = country
          new_headquarter.save!
          @company.headquarter_id = new_headquarter.id
        else
          @company.headquarter_id = headquarter.id
        end

        begin
          @company.save!
          @new_stat.company_id = @company.id
          @new_stat.save!
          flash[:notice] = "Thank you for your contribution!"
          redirect_to new_user_path and return
        rescue => exception
          Honeybadger.notify(exception)
          p exception
          p exception.message
          flash[:notice] = "Sorry something went wrong with you submission"
          redirect_to :back and return
        end # end company.save!
      end # end AR transaction
    end # end if/else

  end

  def charts
    @companies = Company.order(:name).select(&:approved?)

    gon.company_names   = @companies.map(&:name)
    gon.female_eng_nums = @companies.map(&:number_of_female_eng)
    gon.male_eng_nums  = @companies.map(&:number_of_male_eng)
  end

  def top_cities
    @hq_cities      = ActiveRecord::Base.connection.execute("SELECT c.headquarter_id, COUNT(c.headquarter_id), hq.city, hq.state, hq.country FROM companies as c JOIN headquarters as hq WHERE c.headquarter_id = hq.id GROUP BY headquarter_id ORDER BY COUNT(headquarter_id) DESC;")

    count = []
    hq_ids = []
    @hq_cities.each do |sql|
      hq_ids << sql.first
      count << sql[1]
    end
    gon.count = count
    hqs = Headquarter.where(id: hq_ids)
    gon.hq_female_ratio = hqs.map {|hq| hq.average_female_ratio*100}
    gon.hq_names = hqs.map(&:location_string)
  end

  def csv
    @companies = Company.all
    respond_to do |format|
      format.html
      format.csv do
        output = CSV.generate do |csv|
          csv << ['Name', 'Public/Private', 'URL', 'City', 'State', 'Country', 'Number of Female Software Engineers', 'Number of Male Software Engineers', 'Total Number of Software Engineers' ,'Total Company Size']

          @companies.each do |c|
            csv << [
              c.name, c.is_public ? 'Public' : 'Private', c.url, c.headquarter.city, c.headquarter.state, c.headquarter.country, c.number_of_female_eng, c.number_of_male_eng, c.number_of_eng, c.company_size_tier.range
            ]
          end
        end

        send_data output, filename: "fedup_company_list.csv", type: 'text/csv'
      end
    end
  end
end

app/views/companies/charts.html.haml
= stylesheet_link_tag    'charts'

.chart-wrapper
  #bar-chart

:javascript
  $(function () {

    $('#bar-chart').highcharts({
      chart: {
        type: 'bar'
      },
      colors: ['#434348', '#00A064'],
      credits: { enabled: false },
      title: {
        text: 'Female Engineers Percentage by Companies',
        x: 120
      },
      xAxis: {
        categories: gon.company_names
      },
      yAxis: [{
        min: 0,
        max: 100,
        title: {
          text: null
        },
        minTickInterval: 10,
        opposite: true,
        labels: {
          format: '{value}%'
        }
      },
      {
        min: 0,
        max: 100,
        minTickInterval: 10,
        labels: {
          format: '{value} %'
        },
        title: {
          text: 'Female/Male Engineers Distribution'
        },
        labels: {
          format: '{value}%'
        }
      }],
      tooltip: {
        pointFormat: '<span style="color:{series.color}">{series.name}</span>: <b>{point.y}</b> ({point.percentage:.0f}%)<br/>',
        valueSuffix: ' engineers'
      },
      legend: {
        reversed: true,
        align: 'center',
        x: 150
      },
      plotOptions: {
        series: {
            stacking: 'percent'
        }
      },
      series: [{
        name: 'Male Engineers',
        data: gon.male_eng_nums
      }, {
        name: 'Female Engineers',
        data: gon.female_eng_nums
      }]
    });
  });

app/views/companies/cities.html.haml
.chart-wrapper
  #map-chart

:javascript
  $(function () {
    $('.chart-wrapper').highcharts({
      chart: {
        type: 'column'
      },
      credits: { enabled: false },
      title: {
        text: 'Top Startup Cities'
      },
      subtitle: {
        text: 'By headquarter location'
      },
      xAxis: {
        categories: gon.hq_names,
        crosshair: true
      },
      yAxis: {
        min: 0,
        title: {
            text: 'Female Engineer Percentage'
        }
      },
      tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.0f}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
      },
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0
        },
        series: {
          borderWidth: 0,
          dataLabels: {
            enabled: true,
            format: '{point.y:.0f}'
          }
        }
      },
      series: [{
        name: 'Total number of companies',
        data: gon.count
      }, {
        name: 'Average Female Engineer % in the Area',
        data: gon.hq_female_ratio
      }]
    });
  });

app/views/companies/index.html.haml
= stylesheet_link_tag    'charts'

.splash-container
  .splash
    .pure-g
      .l-box.pure-u-1.pure-u-md-1-3.pure-u-lg-1-4
        %ul#nav-section
          %li
            = link_to("Female vs. Male Software Engineer Ratio", {controller: "companies", action: "charts"},'data-no-turbolink' => true, id: "pie-chart-link")
          %li
            = link_to("Female Software Engineer Around the World", {controller: "companies", action: "top_cities"},'data-no-turbolink' => true, id: "city-chart-link")
          %li
            = link_to("Startup Roudup: Who have the most female engineers?", {controller: "companies", action: "charts"},'data-no-turbolink' => true, id: "company-chart-link")
          %li
            = link_to("View Complete Data", {controller: "companies", action: "charts"},'data-no-turbolink' => true)
          %li
            = link_to("Download the Dataset", download_stats_path(format: :csv), id: "company-chart-link")

      .l-box.pure-u-1.pure-u-md-2-3.pure-u-lg-3-4
        #pie-chart{style: "width:100%;"}
        #city-chart{style: "width:70%;"}
        #company-chart{style: "width:70%;"}
      .l-box.pure-u-1
        %p.splash-subhead
          = link_to("Join the revolution", about_path)
          and help to change the face of software engineering
        %p
          %a.pure-button.pure-button-primary{:href => "companies/new"} Add Your Company
.content-wrapper
  .content
    %h2.content-head.is-center As a female in Software Engineering, I feel...
    .pure-g
      - @thoughts.each do |thought|
        .l-box.pure-u-1.pure-u-md-1-2.pure-u-lg-1-4
          %blockquote.quotes
            = "... " + thought.thoughts
    %p
      .l-box.pure-u-sm-1-3.pure-u-md-2-5
      .l-box.pure-u-sm-1-3.pure-u-md-1-5
        %a.pure-button.pure-button-primary{:href => "users/new"} What's your thought?
      .l-box.pure-u-sm-1-3.pure-u-md-2-5

  .content
    .pure-g
      .pure-u-1
        %h3.content-head.is-center
          Share the Cause
      .pure-u-1
        %h3.content-head.is-center
          Change the face of Software Engineering
      .pure-u-1-3.pure-u-md-11-24
      .pure-u-1-3.pure-u-md-1-24.share-links
        .pure-u-1
          .fb-share-button{"data-href" => "/", "data-layout" => "button"}
        .pure-u-1
          %a{href: "https://twitter.com/share", class:"twitter-share-button", "data-text" => "Support female in software engineering!", "data-size" => "large", "data-hashtags" => "WeAreFEDUP,PledgeForParity"}
      .pure-u-1-3.pure-u-md-12-24

  .footer.l-box.is-center
    %span Made with <i class="fa fa-heart"></i> by
    %a{ href: "http://shinshinwu.github.io", title: "Anna Wu", target: "_blank" }
      Anna Wu


:javascript
  $(function () {

    $("#city-chart").hide();
    $("#company-chart").hide();

    $(window).resize(function() {
      $("#city-chart").css({'width': '100%'});
      $("#company-chart").css({'width': '100%'});
    });

    $("#pie-chart-link").hover(function(){
      $("#pie-chart").show();
      $("#city-chart").hide();
      $("#company-chart").hide();
    });

    $("#city-chart-link").hover(function(){
      $("#city-chart").show();
      $("#pie-chart").hide();
      $("#company-chart").hide();
    });

    $("#company-chart-link").hover(function(){
      $("#company-chart").show();
      $("#city-chart").hide();
      $("#pie-chart").hide();
    });

    $('#pie-chart').highcharts({
        chart: {
            plotBackgroundColor: '#F7F7F7',
            plotShadow: false,
            type: 'pie'
        },
        colors: ['#00A064', '#434348'],
        credits: { enabled: false },
        exporting: { enabled: false },
        title: {
            text: 'Female vs. Male Software Engineer Ratio'
        },
        subtitle: {
        text: 'Based on <span style="color:red;font-weight:bold;">' + gon.stats_count + '</span> unaltered user submitted data across <span style="color:red;font-weight:bold;">' + gon.companies_count + '</span> companies'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                }
            }
        },
        series: [{
            name: 'Percentage',
            colorByPoint: true,
            tooltip: {
              pointFormat: '<b>{point.percentage:.1f}%</b>',
              useHTML: true
            },
            data: [{
            name: 'Female Engineers',
            y: gon.female_percentage,
            sliced: true,
            selected: true,
            dataLabels: {
              format: gon.female_engineers_num + ' <b>{point.name}</b><br />{point.percentage:.1f} %'
            }
            }, {
                name: 'Male Engineers',
                y: gon.male_percentage,
                dataLabels: {
                  format: gon.male_engineers_num + ' <b>{point.name}</b><br />{point.percentage:.1f} %'
                }
            }]
        }]
    });

    $('#city-chart').highcharts({
      chart: {
        type: 'column'
      },
      colors: ['#434348', '#00A064'],
      credits: { enabled: false },
      exporting: { enabled: false },
      title: {
        text: 'Top Startup Cities'
      },
      subtitle: {
        text: 'By headquarter location'
      },
      xAxis: {
        categories: gon.hq_names
      },
      yAxis: [{
        min: 0,
        title: {
            text: 'Number of Startups'
        }
      },{
        min: 0,
        max: 100,
        title: {
          text: 'Avg Female Engineer %'
        },
        labels: {
          format: '{value}%'
        },
        opposite: true
      }],
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0
        },
        series: {
          borderWidth: 0,
          dataLabels: {
            enabled: true,
            format: '{point.y:.0f}'
          }
        }
      },
      series: [{
        name: 'Number of Startups in the Area',
        data: gon.count,
        tooltip: {
          pointFormat: '<b>{point.y:.0f} Companies</b>',
          useHTML: true
        }
      }, {
        name: 'Average Female Engineer % in the Area',
        data: gon.hq_female_ratio,
        dataLabels: {
          format: "{y:.0f}%"
        },
        tooltip: {
          pointFormat: '<b>{point.y:.0f}% of Female Engineers</b>',
          useHTML: true
        }
      }]
    });

    $('#company-chart').highcharts({
      chart: {
        type: 'column'
      },
      colors: ['#00A064', '#434348'],
      credits: { enabled: false },
      exporting: { enabled: false },
      title: {
        text: 'Top Companies'
      },
      subtitle: {
        text: 'By Female Software Engineer Ratio '
      },
      xAxis: {
        categories: gon.company_names,
        crosshair: true
      },
      yAxis: {
        min: 0,
        labels: {
          format: '{value}%'
        },
        title: {
            text: 'Female Engineer Percentage'
        }
      },
      tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.0f}%</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
      },
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0
        },
        series: {
          borderWidth: 0,
          dataLabels: {
            enabled: true,
            format: '{point.y:.0f}%'
          }
        }
      },
      series: [{
        name: 'Female Engineers Percentage',
        data: gon.female_ratio
      }]
    });
  });

app/views/companies/map.html.haml
.chart-wrapper
  #map-chart

:javascript
  $(function () {
    $('.chart-wrapper').highcharts({
      chart: {
        type: 'column'
      },
      credits: { enabled: false },
      exporting: { enabled: false },
      title: {
        text: 'Top Startup Cities'
      },
      subtitle: {
        text: 'By headquarter location'
      },
      xAxis: {
        categories: gon.hq_names,
        crosshair: true
      },
      yAxis: {
        min: 0,
        title: {
            text: 'Female Engineer Percentage'
        }
      },
      tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.0f}</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
      },
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0
        },
        series: {
          borderWidth: 0,
          dataLabels: {
            enabled: true,
            format: '{point.y:.0f}'
          }
        }
      },
      series: [{
        name: 'Total number of companies',
        data: gon.count
      }, {
        name: 'Average Female Engineer % in the Area',
        data: gon.hq_female_ratio
      }]
    });
  });

app/views/companies/new.html.haml
.content
  %h2.content-head.is-center Your Company's Profile
  = form_for @company, url: {action: "create"}, html:{class: 'form pure-form pure-form-stacked center'} do |f|
    %fieldset
      .pure-g
        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          %legend The Basics
        .pure-u-1.pure-u-md-1-5

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          = f.label :url, 'Company URL*'
          .pure-u-1
            .pure-u-1-24.pure-u-md-1-24#http
              http://
            .pure-u-20-24.pure-u-md-22-24
              = f.text_field :url, :placeholder => 'google.com', :required => true, id: 'url'
        .pure-u-1.pure-u-md-1-5

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-2-5
          = f.label :name, "Company Name*"
          .pure-u-23-24
            = f.text_field :name, :placeholder => 'Google', :required => true
        .pure-u-1.pure-u-md-2-5
          = f.label :is_public, "Public/Private Company?"
          .pure-u-1
            = f.select :is_public, options_for_select([['Public', 'true'], ['Private', 'false']]), :required => true

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          %legend The Location
        .pure-u-1.pure-u-md-1-5

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          %label{:for => "country"} Country*
          .pure-u-1
            = select_tag "company[headquarter][country]", options_from_collection_for_select(@countries, 'last', 'first'), prompt: "Select Country", :required => true
        .pure-u-1.pure-u-md-1-5

        .pure-u-1#headquarter-state
          .pure-u-md-1-5
          .pure-u-md-3-5
            %label{:for => "state"} State*
            .pure-u-1
              = select_tag "company[headquarter][state]"
          .pure-u-md-1-5

        .pure-u-1#headquarter-city
          .pure-u-1.pure-u-md-1-5
          .pure-u-1.pure-u-md-3-5
            %label{:for => "state"} City*
            .pure-u-1
              = select_tag "company[headquarter][city]"
          .pure-u-1.pure-u-md-1-5

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          %legend The Numbers
        .pure-u-1.pure-u-md-1-5

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          .pure-u-1.pure-u-md-7-24
            = f.label :company_size_tier_id, 'What is your company size?*'
            .pure-u-9-24.pure-u-md-14-24
              = f.select :company_size_tier_id, @company_size_tier.collect {|tier| [tier.range, tier.id]}, :required => true
            .pure-u-5-24.pure-u-md-3-24#employees
              employees
            .pure-u-4-24.pure-u-md-7-24
          .pure-u-17-24
        .pure-u-1.pure-u-md-1-5

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          .pure-u-1
            %label{:for => "state"} How many software engineers does your company have?*
            %p
              %span Software Engineers are the people who are actively contributing to your company's code base.
              %a{href: "https://www.nczonline.net/blog/2012/06/28/whats-a-software-engineer-anyway/", target: "_blank"} Read More
            = number_field_tag "company[company_staff_stat][num_eng]", nil, :min => 1, :max => 100000, :required => true
        .pure-u-1.pure-u-md-1-5

        .pure-u-1.pure-u-md-1-5
        .pure-u-1.pure-u-md-3-5
          .pure-u-1
            %label{:for => "state"} How many of those engineers are female?*
            = number_field_tag "company[company_staff_stat][num_female_eng]", nil, :min => 0, :max => 100000, :required => true
        .pure-u-1.pure-u-md-1-5

          / ask if they are engineers and if they are, what are their gender, language and salary if they wish to report
        .pure-u-1.pure-u-md-2-5
        .pure-u-1.pure-u-md-1-5
          = f.submit "Submit", :class => 'button pure-button'
        .pure-u-1.pure-u-md-2-5

:javascript
  $(function () {

    function location_options_reset (){
      $('#headquarter-state').hide();
      $('#headquarter-city').hide();
      $("#company_headquarter_state").find('option').remove();
      $("#company_headquarter_city").find('option').remove();
    };

    location_options_reset();

    $('#company_headquarter_country').change(function(e) {
      location_options_reset();
      var country_code = $(this).val();
      var url = '/companies/' + country_code + '/states'
      $.getJSON(url, function(data){
        if (!jQuery.isEmptyObject(data)) {
          var optionsValues = '<option selected>Select State</option>'
          $.each(data, function(code, name){
            optionsValues += '<option value="' + code + '">' + name + '</option>'
          });
          $('#company_headquarter_state').html(optionsValues);
          $("#company_headquarter_state").attr('required','required');
          $('#company_headquarter_city').html('<option selected>Select Cities</option>');
          $('#headquarter-state').show();
        };
      });
    });

    $('#company_headquarter_state').change(function(e) {
      $('#headquarter-city').hide();
      $("#company_headquarter_city").find('option').remove();
      var state_code = $(this).val();
      var url = '/companies/' + state_code + '/cities'
      $.getJSON(url, function(data){
        if (!jQuery.isEmptyObject(data)) {
          var optionsValues = '<option selected>Select Cities</option>'
          $.each(data, function(key, name){
            optionsValues += '<option value="' + name + '">' + name + '</option>'
          });
          $('#company_headquarter_city').html(optionsValues);
          $("#company_headquarter_city").attr('required','required');
          $('#headquarter-city').show();
        };
      });
    });

  });

app/views/companies/top_cities.html.haml
= stylesheet_link_tag    'charts'

.chart-wrapper
  #bar-chart

:javascript
  $(function () {
    $('#bar-chart').highcharts({
      chart: {
        type: 'bar'
      },
      colors: ['#434348', '#00A064'],
      credits: { enabled: false },
      exporting: { enabled: false },
      title: {
        text: 'Startup Cities'
      },
      subtitle: {
        text: 'By headquarter location'
      },
      xAxis: {
        categories: gon.hq_names,
        title: {
          text: null
        }
      },
      yAxis: [{
        min: 0,
        title: {
            text: 'Number of Startup Companies'
        },
        labels: {
          overflow: 'justify'
        },
        opposite: true
      },{
        min: 0,
        max: 80,
        title: {
          text: 'Avg Female Engineer %'
        },
        labels: {
          format: '{value}%'
        }
      }],
      legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'top',
        x: -40,
        y: 200,
        floating: true,
        borderWidth: 1,
        backgroundColor: '#FFFFFF',
        shadow: true
      },
      plotOptions: {
        bar: {
          dataLabels: {
            enabled: true,
            format: '{point.y:.0f}'
          }
        }
      },
      series: [{
        name: 'Number of Startups in the Area',
        data: gon.count,
        tooltip: {
          pointFormat: '<b>{point.y:.0f} Companies</b>',
          useHTML: true
        }
      }, {
        name: 'Average Female Engineer % in the Area',
        data: gon.hq_female_ratio,
        dataLabels: {
          format: "{y:.0f}%"
        },
        tooltip: {
          pointFormat: '<b>{point.y:.0f}% of Female Engineers</b>',
          useHTML: true
        }
      }]
    });
  });