config/routes.rb
Rails.application.routes.draw do

  root 'companies#index'
  get '/auth/github/callback' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', :as => :logout
  get 'about' => 'abouts#index'

  resources :companies, only: [:index, :new, :create] do
    collection do
      get '/stats', to: 'companies#charts'
      get '/top-cities', to: 'companies#top_cities'
      get '/:country_code/states', to: 'companies#states'
      get '/:state_code/cities', to: 'companies#cities'
    end
  end

  get 'download/stats', to: 'companies#csv', constraints: {format: :csv}

  resources :users, only: [:new, :update] do
    collection do
      post '/new', to: 'users#update'
      get '/profile', to: 'users#show'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Career Bootcamp - Where you kickstart your career">
  <title>FED-UP Female Engineer Disparities</title>
  <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= yield :stylesheets %>
  <%= include_gon %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/modules/data.js"></script>
  <script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>
  <!-- twitter share -->
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  <script>(function(d, s, id) {var js, fjs = d.getElementsByTagName(s)[0];if (d.getElementById(id)) return;js = d.createElement(s); js.id = id;js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'facebook-jssdk'));</script>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="fb-root"></div>
  <header class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
      <a data-no-turbolink="true" class="pure-menu-heading" href="/">FED <i class="fa fa-code"></i> UP <span id="subtitle" style="text-transform:none;font-weight:300;font-size:13px;color:#8B8C8D">Female Engineer Disparities</span></a>
      <ul class="pure-menu-list">
        <li class="pure-menu-item"><%= link_to "Home", { controller: "companies", action: "index"},'data-no-turbolink' => true, class: "pure-menu-link" %></li>
        <li class="pure-menu-item"><%= link_to "About", about_path, class: "pure-menu-link" %></li>
        <% if logged_in? %>
          <li class="pure-menu-item">Welcome <%= current_user.name %></li>
          <li class="pure-menu-item"><%= link_to "Log out", logout_path, method: "delete", :class => "pure-menu-link" %></li>
        <% else %>
          <li class="pure-menu-item"><%= link_to "Sign Up/Log In", "/auth/github", :class => "pure-menu-link" %></li>
        <% end %>
      </ul>
    </div>
  </header>

  <div class="content">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <%= yield %>
  </div>

  <div class="footer l-box is-center">
    <span>Made with <i class="fa fa-heart"></i> by </span>
    <a href="http://shinshinwu.github.io" target="_blank" title="Anna Wu">Anna Wu</a>
  </div>

  <%= yield :javascripts %>
  <script>
    // google analytics tracking
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74819010-1', 'auto');
    ga('send', 'pageview');
  </script>
</body>
</html>